### ISSUE TITLE
encountered problem while running project

### ISSUE THREAD

**Issue by sourabh1031** [danthareja/contribute-to-open-source-server#2]
i faced errors while running your project(i.e.contribute to open source) into my system since i am a newbie i can,t understand the errors please help.
![2017-12-15 1](https://user-images.githubusercontent.com/25590627/34049003-c7ef94da-e1db-11e7-8bbb-7e829b2f42c7.png)

**Comment by danthareja** [comment]
It looks like you've figured this one out, @sourabh1031. I'm going to leave a comment explaining this error for the future reference of anyone searching this issue.

These errors are coming from [ESLint](https://eslint.org/), a tool that checks your code against certain style rules

 In order to understand this particular error message, you must understand a small intricacy about your code. Every line of code ends with a certain hidden character, which can differ based on the operating system you are using when you write the code.

This message basically says that it expects the "Unix" style of hidden character, automatically typed when developing on a Linux or Mac operating system, but it found the "Windows" style of hidden character. This makes sense, because you are developing on the Windows operating system.

How are you supposed to change a hidden character? Luckily, ESLint makes this easy, and has a command that can automatically fix certain style errors like this one.

Run the following command
```
npm run lint -- --fix
```

And watch these errors magically disappear!
