### ISSUE TITLE
Command prompt stops taking input

### ISSUE THREAD

**Issue by aditya-sahu** [danthareja/contribute-to-open-source-server#4]
The command prompt stops taking input after I write the command you asked: 
`npm test -- --watch`
I am unable to write further commands. It looks like this:
![capture1](https://user-images.githubusercontent.com/32958570/34528909-638b0ca0-f0d0-11e7-8cfa-24c856ee66f1.JPG)

**Comment by danthareja** [comment]
Nice find @aditya-sahu!

What you're experiencing is actually the expected behavior for this command. Adding the `--watch` flag makes the test command a *long-running process*, which means it will suspend input (as you've noticed) and keep running in your terminal window until you kill it (with `ctrl-C`).

There are many reasons why a command might start a long-running process. This particular command constantly watches your files for any changes, and automatically runs the test command. In order to watch the files, it has to keep running.

**The easiest solution is to open a new tab in your terminal.** Now you're even more of a hacker and can have multiple long-running processes going while you write your commands  🎉
