### ISSUE TITLE
Grammatical error in CONTRIBUTING.md

### ISSUE THREAD

**Issue by DevastatingDj** [danthareja/contribute-to-open-source-server#7]
Hey there! This is my first time creating an issue. There is a grammatical error in CONTRIBUTING.md in the "Submit a pull request" part in https://github.com/danthareja/contribute-to-open-source. It's in the first line "Well, in order to fix an issue **the** in the main...". Make the changes accordingly or allow me make the changes in the master branch.

**Comment by danthareja** [comment]
Thanks for the report @DevastatingDj, I'll get to it shortly.

**Comment by theofilos-mazidzoglou** [comment]
Hi danthareja! I was just trying to create a pull request to the master branch for the same issue, but I see someone has beaten me to it.
There is another grammatical error a few words later in the same sentence:
"Well, in order to fix an issue **the** in the main project, you want to change **to** the original code."
Neither of the two words in bold need to be there.

Thanks for helping us get acquainted with Git and Github!

**Comment by danthareja** [comment]
Thanks for the reminder @theomaz, this one had dropped off my radar.

**Comment by danthareja** [comment]
Hey @DevastatingDj  and @theomaz,

I finally got around to making the changes you brought up a while ago. Something about 2020, new year, new me maybe inspired dusting this repo off.

https://github.com/danthareja/contribute-to-open-source/commit/baadde147752d62ae7c024749e24dd922a890505
and 
https://github.com/danthareja/contribute-to-open-source/commit/48d0d2e9ded21b8fc3cc4d5c8d2397efd46d9340

you both are now forever immortalized in the commit history, thanks for helping make this project better
